from enum import Enum

class WebhookEventCode(Enum):
    BOARD_CREATE = "BOARD_CREATE"
    BOARD_DELETE = "BOARD_DELETE"
    COLUMN_CREATE = "COLUMN_CREATE"
    COLUMN_EDIT = "COLUMN_EDIT"
    COLUMN_DELETE = "COLUMN_DELETE"
    TICKET_CREATE = "TICKET_CREATE"
    TICKET_EDIT = "TICKET_EDIT"
    TICKET_DELETE = "TICKET_DELETE"